/**
 * @license
 * Copyright DreamDEX S.A.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/somnia-chain/dreamdex-bot-kit/blob/main/LICENSE
 */

// Quickstart: pick a strategy, network, and market, and this writes a ready-to-run
// `.env` at the repo root. It generates a THROWAWAY key so the bot runs immediately
// in dry-run (safe, logs only, never funded). Replace it with your own funded key
// before setting DRY_RUN=false.
//
// Interactive:      npm run quickstart
// Non-interactive:  node scripts/quickstart.mjs --strategy starter --network testnet --symbol SOMI:USDso --yes
//
// When a flag is omitted and you're at a real terminal, it asks; otherwise it uses
// the default. If a root .env already exists, overwriting needs a "y" (or --yes).

import { createInterface } from "node:readline/promises";
import { randomBytes } from "node:crypto";
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = join(ROOT, ".env");

// strategy → the env var it reads for its market symbol
const STRATEGIES = {
  starter: { symbolVar: "SYMBOL", defaultSymbol: "SOMI:USDso" },
  "market-making": { symbolVar: "MM_SYMBOL", defaultSymbol: "SOMI:USDso" },
  grid: { symbolVar: "GRID_SYMBOL", defaultSymbol: "SOMI:USDso" },
  momentum: { symbolVar: "MOM_SYMBOL", defaultSymbol: "WETH:USDso" },
  "mean-reversion": { symbolVar: "MR_SYMBOL", defaultSymbol: "WETH:USDso" },
  twap: { symbolVar: "TWAP_SYMBOL", defaultSymbol: "SOMI:USDso" },
  ensemble: { symbolVar: "SYMBOL", defaultSymbol: "WETH:USDso" },
  treasury: { symbolVar: "SYMBOL", defaultSymbol: "SOMI:USDso" },
  "yield-optimizer": { symbolVar: "YO_SYMBOL", defaultSymbol: "SOMI:USDso" },
};

function parseFlags(argv) {
  const f = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--yes" || a === "-y") f.yes = true;
    else if (a.startsWith("--")) {
      const key = a.slice(2);
      const val = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[(i++, i)] : "true";
      f[key] = val;
    }
  }
  return f;
}

async function main() {
  const flags = parseFlags(process.argv.slice(2));
  const interactive = process.stdin.isTTY && !flags.strategy && !flags.network && !flags.symbol;
  const rl = interactive ? createInterface({ input: process.stdin, output: process.stdout }) : null;
  const ask = async (q, def) => {
    if (!rl) return def;
    const a = (await rl.question(`${q}${def ? ` [${def}]` : ""}: `)).trim();
    return a || def;
  };

  console.log("\n  DreamDEX Bot Kit — quickstart");
  console.log("  Generates a dry-run .env so you can run a bot in ~60s.\n");

  if (existsSync(ENV_PATH)) {
    let ok = flags.yes === true;
    if (!ok && rl) {
      const ans = (await ask("A root .env already exists. Overwrite? (y/N)", "N")).toLowerCase();
      ok = ans === "y" || ans === "yes";
    }
    if (!ok) {
      console.log("A root .env already exists — not overwriting. Re-run with --yes to replace it.");
      rl?.close();
      return;
    }
  }

  let strategy = flags.strategy ?? (await ask(`Strategy (${Object.keys(STRATEGIES).join(" / ")})`, "starter"));
  if (!STRATEGIES[strategy]) {
    console.log(`Unknown strategy "${strategy}", using "starter".`);
    strategy = "starter";
  }
  const netRaw = flags.network ?? (await ask("Network (testnet / mainnet)", "testnet"));
  const net = String(netRaw).toLowerCase() === "mainnet" ? "mainnet" : "testnet";
  const { symbolVar, defaultSymbol } = STRATEGIES[strategy];
  const symbol = flags.symbol ?? (await ask("Market symbol", defaultSymbol));
  rl?.close();

  // Throwaway key: lets dry-run derive an address and read the chain. NEVER fund it.
  const throwaway = "0x" + randomBytes(32).toString("hex");

  const content = [
    "# Generated by `npm run quickstart`. Safe defaults: dry-run, testnet.",
    "#",
    "# WARNING: PRIVATE_KEY below is a THROWAWAY key for DRY-RUN reads only. It is",
    "#    NOT funded and must NOT be used for real trading. Before you set",
    "#    DRY_RUN=false, replace it with your own funded key (and never commit it).",
    "",
    `NETWORK=${net}`,
    "DRY_RUN=true",
    `PRIVATE_KEY=${throwaway}`,
    "",
    `${symbolVar}=${symbol}`,
    "",
  ].join("\n");

  writeFileSync(ENV_PATH, content);

  console.log(`  Wrote ${ENV_PATH}`);
  console.log(`    strategy=${strategy}  network=${net}  ${symbolVar}=${symbol}  DRY_RUN=true\n`);
  console.log("  Next:");
  console.log(`    npm run dev -w ${strategy}      # runs in dry-run — logs orders, sends nothing\n`);
  console.log("  When the logs look right: edit .env → set your own funded PRIVATE_KEY and DRY_RUN=false.");
  if (strategy === "starter") {
    console.log("  Edit your logic in strategies/starter/src/strategy.ts (the decide() function).");
  }
  console.log("");
}

main().catch((e) => { console.error(`quickstart failed: ${e?.message ?? e}`); process.exit(1); });
